# Generated by Django 6.1 on 2026-08-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_dsaquestion_eligibility_webdevitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsaquestion',
            name='topic',
            field=models.TextField(),
        ),
    ]
